name: opendap
channels:
  - conda-forge
dependencies:
  - python=3.10
  - xarray=2024.1.0
  - dask
  - dask-gateway
  - graphviz
  - distributed
  - h5py>= 3.9
  - matplotlib-base
  - seaborn
  - hvplot
  - pyproj
  - bqplot
  - zarr
  - cartopy
  - pynco
  - joblib
  - pystac-client
  - pydap
  - ipyleaflet
  - dask-labextension
  - jupyter-server-proxy
  - ipywidgets
  - jupyterlab>4
  - pooch
  - earthaccess>=0.8.2
  - pqdm
  - s3fs
  - nbgitpuller
  - pip
  - pip:
    - netcdf4==1.6.5
platforms:
  - linux-64
