name: opendap
channels:
  - conda-forge
dependencies:
  - python=3.10
  - xarray=2024.1.0
  - certifi=2023.11.17
  - cftime=1.6.3
  - dask
  - dask-gateway
  - graphviz
  - distributed
  - rioxarray
  - h5py>= 3.9
  - geoviews
  - matplotlib-base
  - seaborn
  - hvplot
  - datashader
  - pyproj
  - bqplot
  - geopandas
  - zarr
  - cartopy
  - pynco
  - rasterio
  - shapely
  - pyresample
  - joblib
  - pystac-client
  - pydap
  - lxml
  - ipyleaflet
  - dask-labextension
  - jupyter-server-proxy
  - ipywidgets
  - jupyter-book
  - jupyterlab>4
  - jupyterlab-myst
  - jupyterhub-singleuser
  - jupyterlab-geojson
  - jupyterlab-favorites
  - jupyterlab-git
  - jupyter-resource-usage
  - jupyterlab-h5web
  - hdf5plugin
  - ipympl
  - pooch
  - earthaccess>=0.8.2
  - pqdm
  - spectral
  - s3fs
  - nbgitpuller
  - awscliv2
  - jupyter-server-proxy
  - jupyter-vscode-proxy
  # https://github.com/jupyterlab/jupyter-collaboration/issues/202
  # - jupyter-collaboration
  - code-server >=3.2
  - pip
  - pip:
    - netcdf4==1.6.5
platforms:
  - linux-64
