name: openscapes
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dask
  - distributed
  - rioxarray
  - xarray>=2022.12
  - h5netcdf
  - netcdf4=1.6.4
  - h5py
  - gdal~=3.6
  - libgdal
  - geoviews
  - matplotlib-base
  - seaborn
  - intake
  - hvplot
  - datashader
  - pyproj
  - bqplot
  - geopandas
  - zarr
  - cartopy
  - pynco
  - rasterio
  - shapely
  - pyresample
  - icepyx
  - joblib
  - pystac-client
  - pydap
  - lxml
  - ipyleaflet
  - dask-labextension
  - jupyterlab>=4.0
  - jupyter-server-proxy
  - jupyterhub-singleuser
  - jupyterlab-geojson
  - jupyterlab-git
  - jupyter-resource-usage
  - jupyter-collaboration
  - jupyterlab-h5web
  - hdf5plugin
  - ipympl
  - conda-lock
  - pooch
  - earthaccess>=0.5.3
  - rasterstats
  - kerchunk
  - rechunker
  - pqdm
  - coiled
  - s3fs
  - nbgitpuller
  - pip
platforms:
  - linux-64
