name: openscapes
channels:
  - conda-forge
dependencies:
  - python=3.10
  # distributed python
  - dask[complete]
  - flox
  - dask-gateway
  - graphviz
  - distributed
  - streamz
  - cachey
  - coiled
  - joblib
  # gis
  - gdal>=3.8
  - pyproj
  - cartopy
  - shapely
  - rasterio
  - pyresample
  - rasterstats
  - spectral
  - scikit-image
  - ipyleaflet
  # build-essential
  - cmake
  - numba
  - nomkl
  - lz4
  - lxml
  # pangeo
  - xarray>=2023.12
  - rioxarray
  - intake
  - geopandas
  - rechunker
  # pangeo-dataviz
  - holoviews
  - geoviews
  - hvplot
  - datashader
  - seaborn
  - matplotlib-base
  - ipympl
  - bqplot
  # backends
  - h5py
  - zarr
  - h5coro
  - kerchunk
  - h5netcdf
  - pynco
  - pydap
  - icepyx
  - harmony-py
  - sliderule>=3.6.0
  - earthaccess>=0.9.0
  - pystac-client
  - itslive
  - s3fs
  # Jupyterlab
  - dask-labextension
  - jupyter-server-proxy
  - jupyter-vscode-proxy
  - ipywidgets
  - jupyter-book
  - jupyterlab>4
  - jupyterlab-myst
  - jupyterhub-singleuser
  - jupyterlab-geojson
  - jupyterlab-favorites
  - jupyterlab-git
  - jupyter-resource-usage
  - jupyterlab-h5web>=12.0.0
  - hdf5plugin
  - conda-lock
  - pooch
  - git>=2.39
  - pqdm
  - nbgitpuller
  - awscliv2
  - certifi=2023.11.17
  - cftime=1.6.3
  # https://github.com/jupyterlab/jupyter-collaboration/issues/202
  - jupyter-collaboration
  - code-server >=3.2
  - quarto
platforms:
  - linux-64
  - osx-64
