name: openscapes
channels:
  - conda-forge
dependencies:
  - python=3.10
  - dask
  - distributed
  - rioxarray
  - xarray>=2022.12
  - h5netcdf
  - netcdf4=1.6.4
  - h5py
  - gdal~=3.6
  - libgdal
  - geoviews
  - matplotlib-base
  - seaborn
  - intake
  - hvplot
  - datashader
  - pyproj
  - bqplot
  - geopandas
  - zarr
  - cartopy
  - pynco
  - rasterio
  - shapely
  - pyresample
  - icepyx
  - joblib
  - pystac-client
  - pydap
  - lxml
  - ipyleaflet
  - dask-labextension
  - jupyterlab<4.0a
  - jupyter-server-proxy
  - jupyterhub-singleuser
  - jupyterlab-geojson
  - jupyterlab-favorites
  - jupyterlab-git
  - jupyter-resource-usage<1.0.0
  - jupyterlab-h5web
  - hdf5plugin
  - ipympl
  - conda-lock
  - pooch
  - earthaccess>=0.5.3
  - sliderule~=3.6.0
  - qgis
  - h5coro
  - itslive
  - rasterstats
  - kerchunk
  - rechunker
  - pqdm
  - spectral
  - scikit-image
  - coiled
  - s3fs
  - nbgitpuller
  - awscliv2
  - jupyter-server-proxy
  - websockify
  - pyopencl
  - ocl-icd-system
  - pip
platforms:
  - linux-64
