name: openscapes
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  # distributed python
  - dask[complete]
  - cubed[diagnostics]
  - dask-geopandas
  - fsspec>=2023.05
  - flox
  - dask-gateway
  - graphviz
  - distributed
  - streamz
  - cachey
  - coiled
  - joblib
  # gis
  - gdal>=3.8
  - leafmap
  - gmt
  - pyproj
  - cartopy
  - shapely
  - rasterio
  - pyresample
  - rasterstats
  - spectral
  - scikit-image
  - ipyleaflet
  # build-essential
  - cmake
  - numba
  - git-lfs
  - nomkl
  - lz4
  - lxml
  # pangeo
  - xarray>=2024.10
  - rioxarray
  - intake
  - intake-xarray
  - intake-erddap
  - geopandas
  - rechunker
  - virtualizarr
  - python-dotenv
  # pangeo-dataviz
  - pyviz_comms
  - geoviews
  - hvplot
  - datashader
  - seaborn
  - matplotlib-base
  - ipympl
  - bqplot
  - lonboard
  # backends
  - h5py>3.11
  - zarr
  - h5coro
  - kerchunk
  - h5netcdf
  - pynco
  - pydap
  - icepyx
  - harmony-py
  - earthaccess>=0.10.0
  - sliderule>=3.6.0
  - earthaccess>=0.14.0
  - pystac-client
  - itslive
  - s3fs
  - fastparquet
  - erddapy
  - copernicusmarine>=2.1.1
  # Jupyterlab
  - python-gist
  - git-lfs
  - dask-labextension
  - jupyter-server-proxy>=4.1.1
  - jupyter-vscode-proxy
  - ipywidgets
  - jupytext
  - jupyter-book
  - jupyterlab>=4.0
  - gh-scoped-creds==4.1
  - jupyterlab-myst
  - jupyterhub-singleuser
  - jupyterlab-geojson
  - jupyterlab-favorites
  - jupyterlab-git
  - jupyter-resource-usage
  - jupyterlab-h5web>=12.0.0
  - hdf5plugin
  - conda-lock
  - pooch
  - git>=2.39
  - pqdm
  - nbgitpuller>=1.2.1
  - ocl-icd-system
  - websockify>=0.10
  - awscliv2
  # https://github.com/jupyterlab/jupyter-collaboration/issues/202
  - jupyter-collaboration
  - code-server >=3.2
  - quarto
  # For admin (cleaning home dirs)
  - escapism
  - xvec
  - shap
  - xgboost
  # we could use more platforms but in the hub only linux-64 is relevant
  - pip 
  - pip:
    - xq
    - jupyterlab-quarto
    - jupyter-desktop-server>=0.1.3
    - jupyterlab-open-url-parameter
    - pigz
    - neonutilities
platforms:
  - linux-64
