name: openscapes
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pangeo-notebook
  - dask
  - distributed
  - rioxarray
  - xarray>=2022.12
  - h5netcdf
  - netcdf4
  - h5py
  - gdal~=3.6
  - libgdal
  - geoviews
  - matplotlib-base
  - seaborn
  - intake
  - hvplot
  - datashader
  - pyproj
  - bqplot
  - geopandas
  - zarr
  - cartopy
  - pynco
  - rasterio
  - shapely
  - pyresample
  - icepyx
  - joblib
  - pystac-client
  - pydap
  - lxml
  - ipyleaflet
  - jupyterlab-geojson
  - jupyterlab-git
  - jupyter-resource-usage
  - jupyterlab-link-share
  - jupyterlab-h5web
  - hdf5plugin
  - ipympl
  - conda-lock
  - pooch
  - earthaccess>=0.4.7
  - rasterstats
  - kerchunk
  - rechunker
  - pqdm
  - coiled
  - s3fs
  - jinja2~=3.0.3
  - nbgitpuller~=1.1.0
  - pip
platforms:
  - linux-64
  - osx-64
