#!/bin/bash -l

set -euo pipefail

# ==== ONLY EDIT WITHIN THIS BLOCK =====

export PANGEO_ENV="openscapes"
export DISPLAY=":1.0"

mkdir -p $HOME/Desktop

cp *.desktop $HOME/Desktop/

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
