name: Build and push Docker image when we do a stable release
on:
  release:
    types: [published]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: "Set Job Environment Variables"
      run: |
        echo "RELEASE_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: "Set up QEMU"
      uses: docker/setup-qemu-action@v2

    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v2

    - name: "Login to Docker Hub"
      uses: docker/login-action@v2
      with:
        username: openscapes
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: "Build and push"
      uses: docker/build-push-action@v4
      with:
        context: ci
        push: true
        tags: openscapes/python:${{ env.RELEASE_DATE }}

    - name: Export Full Conda Environment
      run: |
          docker run openscapes/python:main conda list --export
